// A worked example of an Intelligence Report.
// The branch is fictional and every figure is illustrative. It shows the format, not a real business.

export const example = {
  branch: "Market Street Post Office",
  town: "Anytown (fictional)",
  type: "Mains branch with retail",
  tier: "Intelligence Report",
  reference: "EX-0001",
  date: "Example",
  score: 71,
  grade: "B",
  verdict: "Proceed, with conditions",
  verdictDetail:
    "A sound branch in a busy parade, priced about 10% above what the numbers support. Worth pursuing if the lease and staffing questions come back clean.",
  headlineStats: [
    { value: "£165k", label: "Asking price" },
    { value: "£58k", label: "PO remuneration a year" },
    { value: "4.3", label: "Google rating" },
    { value: "3", label: "Post Offices within 2 miles" },
  ],
  categories: [
    { name: "Footfall", score: 83 },
    { name: "Location", score: 81 },
    { name: "Online reputation", score: 78 },
    { name: "Competition", score: 76 },
    { name: "Remuneration", score: 74 },
    { name: "Infrastructure", score: 72 },
    { name: "Demographics", score: 70 },
    { name: "Future outlook", score: 69 },
    { name: "Risk", score: 66 },
    { name: "Financials", score: 64 },
    { name: "Staffing", score: 62 },
    { name: "Crime", score: 58 },
  ],
  strengths: [
    "Bus stop and GP surgery within 150 metres drive steady footfall.",
    "The nearest full-service competitor is 1.4 miles away.",
    "A bank branch in town is due to close, which should lift banking transactions.",
  ],
  concerns: [
    "Only three years of accounts supplied. Ask for five.",
    "Two long-serving staff transfer under TUPE on above-market rates.",
    "Shop theft is above the national average for this type of area.",
  ],
  financial: {
    askingSplit: [
      { label: "Goodwill & fixtures", value: 120 },
      { label: "Stock (at valuation)", value: 25 },
      { label: "Lease premium", value: 20 },
    ],
    pnl: [
      { item: "Retail gross profit", low: 88, high: 101 },
      { item: "PO remuneration", low: 54, high: 60 },
      { item: "Staff costs", low: -78, high: -71 },
      { item: "Rent, rates & overheads", low: -38, high: -33 },
    ],
    net: { low: 26, high: 57 },
  },
  remuneration: [
    { stream: "Banking & cash", share: 34 },
    { stream: "Mails & parcels", share: 31 },
    { stream: "Bill payments", share: 14 },
    { stream: "Travel money", share: 11 },
    { stream: "Other", share: 10 },
  ],
  staffing: [
    { item: "Wages", value: 61 },
    { item: "Employer NI", value: 6 },
    { item: "Pension", value: 2 },
    { item: "Holiday cover", value: 5 },
    { item: "Training", value: 1 },
  ],
  reviews: {
    rating: 4.3,
    count: 212,
    responseRate: 0,
    positive: ["Friendly staff", "Quick service", "Helpful with parcels"],
    negative: ["Queues at lunchtime", "Cash machine often empty"],
  },
  demographics: [
    { measure: "Aged 65+", local: 24, national: 19 },
    { measure: "Households without a car", local: 31, national: 23 },
    { measure: "Renting", local: 38, national: 35 },
    { measure: "In work", local: 71, national: 75 },
  ],
  crime: {
    monthly: [21, 18, 24, 19, 26, 30, 28, 25, 22, 27, 31, 29],
    split: [
      { type: "Shoplifting", share: 34 },
      { type: "Anti-social behaviour", share: 29 },
      { type: "Violence", share: 21 },
      { type: "Other", share: 16 },
    ],
  },
  competitors: [
    { name: "Competitor A (full service)", miles: 1.4, angle: 40, full: true },
    { name: "Competitor B (Local)", miles: 0.9, angle: 200, full: false },
    { name: "Competitor C (full service)", miles: 1.9, angle: 290, full: true },
    { name: "Supermarket parcel point", miles: 0.6, angle: 120, full: false },
  ],
  footfall: [
    { name: "Bus stop", metres: 40 },
    { name: "GP surgery", metres: 140 },
    { name: "Primary school", metres: 320 },
    { name: "Supermarket", metres: 450 },
    { name: "Railway station", metres: 900 },
  ],
  infrastructure: [
    { item: "Full-fibre broadband", status: "Available" },
    { item: "4G/5G signal", status: "Strong" },
    { item: "Parking", status: "Limited, on-street" },
    { item: "Step-free access", status: "Yes" },
  ],
  outlook: [
    { when: "Next 6 months", event: "Town-centre bank branch closes", effect: "positive" },
    { when: "Next 12 months", event: "320 new homes under construction nearby", effect: "positive" },
    { when: "Next 2 years", event: "Business rates revaluation", effect: "negative" },
    { when: "Ongoing", event: "Parcel volumes shifting to lockers", effect: "negative" },
  ],
  risks: [
    { name: "TUPE staff costs", likelihood: 0.85, impact: 0.6 },
    { name: "Lease renewal terms", likelihood: 0.56, impact: 0.85 },
    { name: "Shop theft", likelihood: 0.7, impact: 0.35 },
    { name: "Competitor opening", likelihood: 0.2, impact: 0.7 },
    { name: "Rates increase", likelihood: 0.55, impact: 0.16 },
  ],
  profitPlan: [
    { step: "Current net profit (midpoint)", value: 41, base: true },
    { step: "Reply to every Google review", value: 3 },
    { step: "Rota matched to footfall", value: 8 },
    { step: "Travel money promotion", value: 4 },
    { step: "Retail range review", value: 6 },
  ],
  negotiation: {
    asking: 165,
    opening: 138,
    target: 148,
    walkAway: 155,
    min: 120,
    max: 175,
    questions: [
      "Can I see five years of accounts and the last 12 months of Post Office remuneration statements?",
      "What is left on the lease, and has the landlord agreed in principle to a renewal?",
      "Which staff transfer, on what contracts, and are there any open grievances?",
      "When was the last Post Office audit, and were there any cash discrepancies?",
    ],
  },
} as const;
